name: Download and Deploy Latest Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

      # Step 3: Fetch the latest release tag
      - name: Get the latest release tag
        id: get_latest_release
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/JebaShinba/Build/releases/latest | jq -r '.tag_name')
          echo "Latest release tag: $LATEST_TAG"
          echo "tag=$LATEST_TAG" >> $GITHUB_ENV

      # Step 4: Debug URL and Tag
      - name: Debug URL and Tag
        run: |
          echo "Using tag: ${{ env.tag }}"
          echo "Constructed URL: https://github.com/JebaShinba/Build/releases/download/${{ env.tag }}/filename.zip"

      # Step 5: Download the release asset
      - name: Download release asset
        run: |
          wget -O filename.zip "https://github.com/JebaShinba/Build/releases/download/${{ env.tag }}/filename.zip"

      # Step 6: Extract the release
      - name: Extract release
        run: |
          unzip filename.zip -d ./deployment

      # Step 7: Deploy the application
      - name: Deploy application
        run: |
          chmod +x ./deploy.sh
          bash ./deploy.sh