name: Download and Deploy Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to download"
        required: true
        default: "v2024.11.28-030854"  # Update this to your latest tag

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Debug URL and Tag
        run: |
          echo "Using tag: ${{ github.event.inputs.tag }}"
          echo "Constructed URL: https://github.com/JebaShinba/Build/releases/download/${{ github.event.inputs.tag }}/filename.zip"

      - name: Download release asset
        run: |
          TAG=${{ github.event.inputs.tag }}
          wget -O filename.zip "https://github.com/JebaShinba/Build/releases/download/${TAG}/filename.zip"

      - name: Extract release
        run: |
          unzip filename.zip -d 

      - name: Deploy application
        run: |
          chmod +x ./deploy.sh
          ./deploy.sh

