name: Detect OS on Windows Self-Hosted Runner
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering
jobs:
  detect-os-windows:
    runs-on: [self-hosted, windows]  # Ensure the runner is Windows-based
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run OS Detection Script
        run: |
          # Run the shell script using Git Bash
          "C:\Program Files\Git\bin\bash.exe" ./demo.sh
