name: Detect OS on Windows Self-Hosted Runner
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering
jobs:
  detect-os-windows:
    runs-on: [self-hosted, windows] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set PowerShell Execution 
        run: |
          C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File

      
      - name: Run OS Detection Script
        run: ./demo.sh