name: Detect OS on 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-os-windows:
    runs-on: [self-hosted, windows] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      

      - name: Run PowerShell Script
        run: |
          # Make sure to replace the path below with the actual location of your PowerShell script
          C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -File "C:\Users\jebas\Build\demo.sh"
      
      - name: Run OS Detection Script
        run: |
          # If you're still using the bash script, ensure you have WSL enabled on the runner
          ./demo.sh
