name: Detect OS on Windows Self-Hosted Runner
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering
jobs:
  detect-os-windows:
    runs-on: [self-hosted, windows]  # Ensure the runner is Windows-based
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run OS Detection Script
        run: |
          # Ensure that we call PowerShell from the correct path
          $powershellPath = "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
          if (Test-Path $powershellPath) {
            & $powershellPath -File ./demo.ps1
          } else {
            Write-Error "PowerShell not found at the expected path"
          }
